# Generated by Django 5.2 on 2025-05-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('user', 'User')], default='user', max_length=20, verbose_name='User Role'),
        ),
    ]
