# Generated by Django 5.2 on 2025-05-11 20:04

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('surface_area', models.PositiveIntegerField(help_text='Area in square meters')),
                ('rooms', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('furnished', models.BooleanField(default=False)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('studio', 'Studio'), ('duplex', 'Duplex'), ('triplex', 'Triplex'), ('penthouse', 'Penthouse'), ('house', 'House'), ('villa', 'Villa'), ('riad', 'Riad'), ('urban_land', 'Urban Land'), ('agricultural_land', 'Agricultural Land'), ('farm_ranch', 'Farm / Ranch'), ('office', 'Office'), ('shop', 'Shop / Commercial Space'), ('warehouse', 'Warehouse / Storage'), ('factory', 'Factory'), ('restaurant', 'Restaurant / Café'), ('hotel', 'Hotel / Guesthouse'), ('building', 'Building'), ('showroom', 'Showroom'), ('parking', 'Parking / Garage')], max_length=50)),
                ('status', models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('sold', 'Sold'), ('rented', 'Rented')], default='for_sale', max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload property photos', upload_to='property_images/')),
                ('is_cover', models.BooleanField(default=False, help_text='Set as cover image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_cover', 'created_at'],
            },
        ),
    ]
